version: '2'

services: 
  web:
    container_name: dockerweb
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "7000:5000"
    volumes: 
      - .:/app
    networks: 
      - aspnetcoreapp-network

  sql:
    container_name: dockerdb
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes: 
      - c:/code/sql:/var/opt/mssql/data
    ports: 
      - "1433:1433"
    environment: 
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: yourStrong(!)Password
    networks: 
      - aspnetcoreapp-network

networks: 
  aspnetcoreapp-network:
    driver: bridge